# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='option',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
